### ISSUE TITLE
Is vandium v4 Lambda proxy compatible with Serverless Framework?

### ISSUE THREAD

**Issue by msteckyefantis** [vandium-io/vandium-node#18]
[Serverless Framework API Gateway docs](https://serverless.com/framework/docs/providers/aws/events/apigateway/)

Doesn't look like it on first glance.

**Comment by dc00p** [comment]
Works fine with Serverless.  Take a lot at the new Server example in the examples folder!

**Comment by msteckyefantis** [comment]
Okay good job Daniel, great to hear, I'll check it out, next time leave [a link](https://github.com/vandium-io/vandium-node/tree/4.x/examples/serverless).🐲

**Comment by msteckyefantis** [comment]
Just tested it using two methods on the same resource, seems to be working fine, thank you👍

Vandium v4 is pretty legit.
