### ISSUE TITLE
Doc improvement suggestions

### ISSUE THREAD

**Issue by msteckyefantis** [vandium-io/vandium-node#19]
**English Improvement Suggestion**

[This doc page](https://github.com/vandium-io/vandium-node/blob/4.x/docs/events/api/README.md)
[on line 60:](https://github.com/vandium-io/vandium-node/blame/4.x/docs/events/api/README.md#L60)

"As you can see, the individual HTTP methods have their own independent... "

You should consider removing the "As you can see" part, or replacing it with "In the above code" or something like that.

**Comment by msteckyefantis** [comment]
**Spacing Improvement Suggestion**

```.js
'use strict';

const vandium = require( 'vandium' );

const User = require( './user' );

const cache = require( './cache' );


exports.handler = vandium.api()
        .GET(

            event => {

                // handle get request
                return User.get( event.pathParameters.name );
            }

        )
        .POST(

            {
                // validate
                body: {

                    name: vandium.types.string().min(4).max(200).required()
                }
            },

            event => {

                // handle POST request
                return User.create( event.body.name );
            }
        )
        .finally(

            () => {

                // close the cache if open - gets executed on every call
                return cache.close();
            }
        );
```

**Comment by msteckyefantis** [comment]
**Doc Content Improvement Suggestion**

Show examples of validation on `headers `, `queryStringParameters` in the code samples for GET requests, or other types. Don't just show `body` validation for POST and PATCH requests.

**Comment by msteckyefantis** [comment]
**Doc Duplicate Key Improvement Suggestion**

[😭](https://github.com/vandium-io/vandium-node/blame/4.x/docs/events/api/responses.md#L78-L79)

**Comment by dc00p** [comment]
Thanks
