### ISSUE TITLE
Difficult to get validated request body as object

### ISSUE THREAD

**Issue by RobBrazier** [vandium-io/vandium-node#24]
I've been trying to use the joi validated request body feature, however instead of the actual request body, I'm getting `{ [String: '{"name":"foobar"}'] name: 'foobar' }` back

```
// [...]
  .PUT({
    body: {
      name: "string"
    }
  }, (event) => {
     // [...]
  })
// [...]
```

I believe it's down to this line: https://github.com/vandium-io/vandium-node/blob/master/lib/event_types/api/validator.js#L22

Is there a reason for using Object.assign instead of straight assigning the value, I tried doing
```
event[this.key] = updated;
```
and it seems to work fine.

**Comment by dc00p** [comment]
`event.body` is a string, and requires requires parsing first. Will be fixed in the 4.3.0 release.

**Comment by RobBrazier** [comment]
It's a string before validation has occurred, however afterwards `event.body` is replaced with the value object returned from joi.

I've tried stringifying and re-parsing the object returned by the validation, however for some strange reason the parsing still returns a string.

Is the plan to keep event.body as a string then, even after validation?

**Comment by dc00p** [comment]
Likely will attempt to convert `event.body`to an object before validation.

**Comment by msteckyefantis** [comment]
@dc00p "Likely will attempt to convert `event.body` to an object before validation."

Don't you mean **AFTER** validation @dc00p ?


I've just been using `const body = JSON.parse( event.body );`,
and that works #swaggy (`body` becomes the object that you would expect it to be).

If you change it, please notify **everybody**, and put it clearly in the documentation.

This would be a breaking change for people like me.

![GitHub Logo](https://media.giphy.com/media/dkXPZ4CFeHcVq/giphy.gif)

**Comment by richardhyatt** [comment]
It will get converted before validation, validated and then updated (if changed by validation rules). Documentation will be updated and this is the reason it will be changed in 4.3 vs the 4.2.x one.

**Comment by msteckyefantis** [comment]
@richardhyatt Alright so just to be clear, what is the rule going to be?

Is it?: If the `event.body` coming in is a stringified object, then it will automatically be converted into an object before validation. Which then means, assuming the validation doesn't change the value's type, the event.body value of the lambda function will already be a parsed object.

**Comment by msteckyefantis** [comment]
Also I've just noticed:


```.js
const Joi = require( 'joi' )
Joi.object().validate( JSON.stringify( { abc: 123 } ) ).value
const object = Joi.object().validate( JSON.stringify( { abc: 123 } ) ).value

// object.abc is 123
```
Joi automatically converts the value to an object!

**Comment by richardhyatt** [comment]
Fix is in the 4.x branch if you would like to try it. If `event.body` is a JSON object, it will be parsed and validated

**Comment by msteckyefantis** [comment]
@richardhyatt  Alright, trying it now.

**Comment by msteckyefantis** [comment]
Yes it works, very nice, thank you!👍

request body without parsing:
```.js
{
    "firstName": "Mikey",
    "lastName": "Stecky-Efantis"
}
```

![Jar Jar](https://i.imgflip.com/zyegx.jpg)

**Comment by RobBrazier** [comment]
yep, looks good to me as well :smile: thanks!
