### ISSUE TITLE
Scheduled event problem

### ISSUE THREAD

**Issue by wasenbr** [vandium-io/vandium-node#29]
Now, when it created a scheduled event to trigger a lambda function, it could set the event variable value. As a trigger input, It could be Matched event, as the vandium identifier expects, but it could be defined as a Json constant.

If I define as a constant, the Vandium does not recorgnise the event and raise a error.

I think the Vandium should be modified to be more flexible with this kind of inputs.

**Comment by richardhyatt** [comment]
Are you using the cloudwatch event to trigger the lambda function or via another event source?

**Comment by wasenbr** [comment]
Yes, I'm using cloudwatch. It has this input options now.

**Comment by richardhyatt** [comment]
Will add an option to disable event validation and allow a JSON constant

**Comment by richardhyatt** [comment]
In the short term, you can use `vandium.generic()` handler

**Comment by wasenbr** [comment]
Great!! Thanks!

I did put the required values to pass in identifier:

account: "1"
region: "us-east-1"
source: "aws.events"
id: "1"
detail-type: "Scheduled Event"

**Comment by richardhyatt** [comment]
Try the code in the 4.x branch:

```js
exports.handler = vandium.scheduled( { customEvent: true }, (event) => {

                    // event will be your defined event

                    // your code here
                });
```
