### ISSUE TITLE
Automatically gzip response

### ISSUE THREAD

**Issue by wasenbr** [vandium-io/vandium-node#30]
Some returns in a API is a very large json and it could be slow to download this data. 

A good feature to Vandium is to have a option to gzip the response automatically. 

It could be a option like

vandium.api().acceptGzip(true)

or better,  by existing the header

accept-encoding: gzip

in the request header.

Or a combination of both.

It could be something like this:

https://www.reszelewski.com/2017/03/serving-gzipped-content-from-aws-lambda.html

A gzip base64 encoded.

**Comment by richardhyatt** [comment]
Added this to the 4.x branch - give it a try and let me know how it works for you

**Comment by wasenbr** [comment]
I did test and occurs a error when the handler returns a object:

TypeError: Not a string or buffer
api_handler.js:293
message:"Not a string or buffer"
stack:"TypeError: Not a string or buffer\n    at zlibBufferSync (zlib.js:235:11)\n    at Object.exports.gzipSync (zlib.js:127:10)\n    at APIHandler.processResult (c:\Projetos\p-docs\api\node_modules\vandium\lib\event_types\api\api_handler.js:288:29)\n    at doBefore.then.then (c:\Projetos\p-docs\api\node_modules\vandium\lib\event_types\handler.js:154:49)\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"
__proto__:Error {name: "TypeError", message: ""}

**Comment by richardhyatt** [comment]
good catch - sorry I missed that case - I'll have it convert the value to a string before gzipping it

**Comment by richardhyatt** [comment]
Added a fix to encode objects that are not Buffer or String instances into JSON strings

**Comment by wasenbr** [comment]
I did test and it's working when te returns is a object.
I did deploy it on API gateway and I have some difficult to make it works.
While I doing that, I did see that now, it is supported natively on API Gateway. 

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html

Maybe it could be a problem if the Vandium automatically encode the response.

I think the auto encoding of the response should by optional, not defined only by the request header.

**Comment by richardhyatt** [comment]
Maybe we should back out the feature - if it's supported by the API Gateway, there's no real case to duplicate the effort

**Comment by wasenbr** [comment]
I agree.

**Comment by richardhyatt** [comment]
Removed this feature since API Gateway supports all the functionality that we require
