### ISSUE TITLE
Feature: Accept and auto parse application/x-www-form-urlencoded content-type for request body

### ISSUE THREAD

**Issue by riotrah** [vandium-io/vandium-node#34]
Are we interested in accepting different content types?

Given that Serverless accepts `application/x-www-form-urlencoded` content-type out of the box as mentioned in the Gitter, it might make sense to allow this content type and offer it parsed like for `application/json`.

## API

`application/x-www-form-urlencoded` could be enabled/disabled via a method on api() like (maybe a *prettier* api could be thought up 🤷‍♀️):

```
export default vandium.api()
        .acceptFormURLEncoded(true)
        .POST( {
                body: {
                    foo: vandium.types.string(),
                }
            },
            (event) => 'hello');
```

Alternately it could just be parsed automatically without config like for json bodies. 

In case other content types are going to be auto-parsed in the future, instead of the `acceptFormURLEncoded()` a general 'bodyRequestContentType()' may be more useful (or perhaps a `@content` key in the `body` validation object?)

## Implementation

It could be done within: https://github.com/vandium-io/vandium-node/blob/a973e3ef98342128a9eca3c1299cbca9c048d3ce/lib/event_types/api/api_handler.js#L108

via another `try` block using the `query-string` module or some other parser.

A more longevity oriented solution may be to pass along a `contentType` arg and have that function do some case handling. 

---

( Not sure if this is a feature or an enhancement )

I can open up a PR if needed upon settling on a non-breaking API.

**Comment by richardhyatt** [comment]
Can you open up a PR and we can get it into the next release.

Thanks

**Comment by riotrah** [comment]
I'm not sure which API suggestion we are interested in - but I'll start with two branches:
1. For automatically parsing 
2. For configured parsing via .formURLEncoded()

**Comment by riotrah** [comment]
Created 4 branches for permutations of the decisions of 
1. which querystring parsing lib to use and 
2. whether the parsing is automatic - like for JSON bodies - or only enabled via a handler method.

Please advise as to which I should open a PR for.

**Comment by richardhyatt** [comment]
I think the parsing should be automatic but have the ability to enable/disable
