### ISSUE TITLE
protection whats tripping it?

### ISSUE THREAD

**Issue by vanerleo** [vandium-io/vandium-node#45]
I have a plain login form and something seems to be tripping protection.
how do i find out what is is exactly thats tripping it?

**Comment by richardhyatt** [comment]
What is the exception? You can catch it and log using the [`onError()`](https://github.com/vandium-io/vandium-node/blob/master/docs/apigateway.md#setting-the-statuscode-for-errors-for-all-http-methods) method.

**Comment by vanerleo** [comment]
if its supposed to be Caught ... i wasn't seeing it ... must be something else .. probably bad serverless deployment
