### ISSUE TITLE
protection is tripped when sending html to be saved : EQUALS_WITH_COMMENT

### ISSUE THREAD

**Issue by vanerleo** [vandium-io/vandium-node#46]
Sending html to backend to be saved.
protection is tripping on EQUALS_WITH_COMMENT
i can see that there is a provision for disabling certain checks but is commented out 

https://github.com/vandium-io/vandium-node/blob/a973e3ef98342128a9eca3c1299cbca9c048d3ce/lib/protect/sql.js

any recommendations? besides turning off ?
can protection be turned off depending on : event.pathParameters.proxy path?

**Comment by richardhyatt** [comment]
Currently, you'd have to disable SQL injection protection - could add the ability to disable programmatically in the next major release.

Can you provide the input that's causing the protection rule to get triggered?

**Comment by vanerleo** [comment]
```
<p>--</p>
```

**Comment by richardhyatt** [comment]
That input doesn't seem to trigger it unless it's encoded.

Are you using the 4.x or an older version?

**Comment by richardhyatt** [comment]
Is this issue still active or should we close?
