### ISSUE TITLE
Feature: generate Set-Cookie response headers from object

### ISSUE THREAD

**Issue by riotrah** [vandium-io/vandium-node#47]
Keeping in theme of offering conveniences for Serverless Framework devs, I propose a feature for handler response objects. If this response object contains an array or object called `[cC]ookies` or `Set-Cookie`, Vandium should auto encode those cookie objects as `Set-Cookie`-formatted headers.

API:
===

Some considerations:

1. The key could be set at the top level of the handler return object, or inside the `headers` object, if present. Not sure what we think is best course of action is if included in both; not sure if it matters.

2. `Set-Cookie` as a key should also be acceptable if the value is not a string.

Implementation:
===

Haven't thought much into implementation details, but I am aware Vandium-node depends on the `cookie` module from `jshttp` so it would be done wherever the automatic resolution of the `statusCode` or `body` keys is done.

**Comment by riotrah** [comment]
Is this a v5.0.0 feature?

**Comment by riotrah** [comment]
And do we want to support response cookie definition for all methods attached to handler ( like `handlerInstance.cookies( { cookie } )` ) or just per-response ?

**Comment by riotrah** [comment]
Finally, do we support error responses setting cookies?

**Comment by richardhyatt** [comment]
Let's add this into the 5.x branch
