### ISSUE TITLE
Feature: jwt Opt-out per handler

### ISSUE THREAD

**Issue by riotrah** [vandium-io/vandium-node#48]
Sometimes we want cross-service jwt acceptance and processing, which is when we activate it in our environment variables. If we have one or two endpoints who do not expect a jwt, it would be nice to offer a jwt opt-out. Perhaps an argument could be made that those endpoints should be deployed as separate services but I see two reasons for offering this features in that case:

1. Enough users are building serverless applications by translating some idioms and mental models over from monolithic applications 

2. If the majority of endpoints in an application need auth but one or two don't, separation out into a separate service shouldn't be enforced. If I have dozens of handlers  the env var jwt opt-in is a great convenience that arguably I shouldn't have to lose for this.

> If I managed to miss it in the docs, please yell at me.

Otherwise, a jwt opt-out per handler would be great.

API:
===
```
api()
.jwt({
	disable: true
})
```

( or something more Vandium-idiomatic to that effect )

Implementation:
===

Have not looked into this yet, but I can take a look if requested to jog my memory of the handler architecture

**Comment by riotrah** [comment]
Can do this one

**Comment by richardhyatt** [comment]
could also change `.jwt()` to accept a boolean to disable the validation - might be a little more intuitive for the user when reading the code. When `.jwt( true )` is supplied, the operation will be the same as `.jwt()` which uses environment variables or other configuration data.

**Comment by riotrah** [comment]
Agree, will get on it.

**Comment by richardhyatt** [comment]
This exists, but not documented, by using `.jwt( { enabled: false } )`.

I do like the idea of passing false: `.jwt( false )`
