### ISSUE TITLE
Feature: Accept array values during APIG schema validation for alternates.

### ISSUE THREAD

**Issue by riotrah** [vandium-io/vandium-node#62]
Currently Vandium is using Joi (via joi json) for schema validation. I've defined all of my schema validations centrally in a model schemas file with each model defined as raw objects so that they can be parsed by both OG Joi and also Vandium as APIG event validation schemas.

Joi supports schema values as arrays, representing a shorthand for .alternates().

I propose we allow Vandium to also accept arrays of Joi schemas.

# API:

```
api()
  .get( { 
    queryStringParameters: { 
      param: [ Vandium.types.string, Vandum.types.number ] 
    },
  }, 
  () => {} );
```

# Implementation Details

[Convert this line](https://github.com/vandium-io/vandium-node/blob/cbf81599d92d067f08ff570c96716fa12e34b173/lib/validation/index.js#L21)

from:

```
else if( utils.isObject( value ) && value.isJoi ) {
```

to: 

```
else if( 
  ( utils.isObject( value ) && value.isJoi ) 
  || ( Array.isArray(value) 
    && value.every( item => utils.isObject( value ) && value.isJoi ) ) 
) {
```

Of course, something less ugly could be conceived too.

**Comment by richardhyatt** [comment]
Will implement
