### ISSUE TITLE
using with serverless-offline

### ISSUE THREAD

**Issue by vanerleo** [vandium-io/vandium-node#7]
gives an error:
"stackTrace":["Error: handleralready exists with name: exec","at Pipeline.add (vandium/lib/pipeline.js:73:19)","at Object.install (vandium/lib/plugins/exec/runner.js:57:14)","at wrapHandler (vandium/lib/index.js:83:18)","at Vandium (vandium/lib/index.js:151:9)","at Object.

**Comment by richardhyatt** [comment]
This exception occurs if you wrap your handler with vandium more than once. Do you have more than 1 handler in the file? Code (with your handler logic removed) might help - you can always PM me via our gitter board: https://gitter.im/vandium-io/vandium if you want to provide information privately.

**Comment by vanerleo** [comment]
run serverless-offline with the --skipCacheInvalidation flag
